// Automatically generated by the bundler tool from c:\Program Files\Microsoft Xbox SDK\Samples\Xbox\Attach\resource.rdf

#define resource_NUM_RESOURCES 1UL

#define resource_JustTurnItOn_OFFSET 32UL
